# Generated by Django 6.1 on 2026-08-26 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('rights', '0002_safetyresponse_alter_actionstep_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('preferred_support_channel', models.CharField(blank=True, choices=[('in_person', 'In Person'), ('phone', 'Phone'), ('remote', 'Online / Remote')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='new', max_length=30)),
                ('citizen_consent_to_share', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partner_referrals', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='partners.partnerorganisation')),
                ('rights_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='rights.rightstopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_referral_status_changes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='referrals.referral')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['organisation', 'status'], name='referrals_r_organis_19f5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['reference'], name='referrals_r_referen_9a56d9_idx'),
        ),
    ]
