# Generated by Django 4.2.29 on 2026-08-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
