# Generated by Django 6.1 on 2026-08-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, max_length=150)),
                ('document_type', models.CharField(choices=[('constitution', 'Constitution'), ('act', 'Act'), ('regulation', 'Regulation'), ('rule', 'Rule'), ('other', 'Other')], default='act', max_length=30)),
                ('jurisdiction', models.CharField(default='Uganda', max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('version_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(default='section', max_length=50)),
                ('section_number', models.CharField(blank=True, max_length=50)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal_knowledge.legaldocument')),
            ],
            options={
                'ordering': ['document', 'order', 'id'],
            },
        ),
    ]
