# Generated by Django 6.1 on 2026-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_key', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], max_length=10)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('ussd', 'USSD'), ('sms', 'SMS'), ('voice', 'Voice')], max_length=20)),
                ('text', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('content_key', 'language', 'channel')},
            },
        ),
    ]
