# Generated by Django 6.1 on 2026-08-25 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelcontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channelcontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='channelcontent',
            index=models.Index(fields=['content_key', 'language', 'channel'], name='content_cha_content_6a8eea_idx'),
        ),
        migrations.AddConstraint(
            model_name='channelcontent',
            constraint=models.UniqueConstraint(fields=('content_key', 'language', 'channel'), name='unique_channel_content'),
        ),
    ]
