# Generated by Django 6.1 on 2026-08-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], max_length=10)),
                ('state', models.CharField(default='language_select', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
