# Generated by Django 6.1 on 2026-08-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='last_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='last_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
