# Generated by Django 4.2.29 on 2026-08-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_ussdsession_last_response_ussdsession_last_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('last_situation_slug', models.SlugField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
