# Generated by Django 4.2.29 on 2026-08-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_smscontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscontext',
            name='discreet',
            field=models.BooleanField(default=False),
        ),
    ]
