# Generated by Django 4.2.29 on 2026-08-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_smscontext_discreet'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscontext',
            name='pending_safety_check',
            field=models.BooleanField(default=False),
        ),
    ]
