# Generated by Django 6.1 on 2026-08-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_smscontext_pending_safety_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('state', models.CharField(default='awaiting_recording', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
