# Generated by Django 6.1 on 2026-08-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_smscontext_pending_safety_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscontext',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
