# Generated by Django 4.2.29 on 2026-08-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_alter_smscontext_id'),
        ('channels', '0006_voicesession'),
    ]

    operations = [
    ]
