# Generated by Django 6.1 on 2026-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_seed_multilingual_ussd_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscontext',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='smscontext',
            name='last_situation_slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
