# Generated by Django 6.1 on 2026-08-27 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_voicesession'),
        ('channels', '0009_seed_multilingual_sms_copy'),
    ]

    operations = [
    ]
