# Generated by Django 4.2.29 on 2026-08-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_merge_0006_alter_smscontext_id_0006_voicesession'),
        ('channels', '0010_merge_20260827_1453'),
    ]

    operations = [
    ]
