# Generated by Django 4.2.29 on 2026-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_merge_20260827_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscontext',
            name='pending_referral_step',
            field=models.CharField(blank=True, choices=[('consent', 'Awaiting consent'), ('district', 'Awaiting district')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='smscontext',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voicesession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
