# Generated by Django 6.1 on 2026-08-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0002_supportservice_alternate_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_type', models.CharField(blank=True, choices=[('legal_aid', 'Legal Aid Organisation'), ('ngo', 'Non-Governmental Organisation'), ('cbo', 'Community-Based Organisation'), ('government', 'Government Institution'), ('law_firm', 'Law Firm'), ('protection_service', 'Protection / Safeguarding Service'), ('mediation_service', 'Mediation / Dispute Resolution Service'), ('other', 'Other')], max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=150)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('headquarters_district', models.CharField(blank=True, max_length=100)),
                ('physical_address', models.TextField(blank=True)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_organisation', to='support.supportservice')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerServiceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('support_channels', models.JSONField(blank=True, default=list)),
                ('districts_served', models.JSONField(blank=True, default=list)),
                ('nationwide', models.BooleanField(default=False)),
                ('free_services', models.BooleanField(default=False)),
                ('appointment_required', models.BooleanField(default=False)),
                ('accepting_referrals', models.BooleanField(default=False)),
                ('weekly_referral_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_configuration', to='partners.partnerorganisation')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=30)),
                ('declaration_accurate', models.BooleanField(default=False)),
                ('declaration_authorised', models.BooleanField(default=False)),
                ('declaration_consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='partners.partnerorganisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_verifications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_partner_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerVerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration Evidence'), ('organisation_identification', 'Organisation Identification'), ('service_evidence', 'Service Evidence'), ('authorised_representative', 'Authorised Representative Evidence'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='partner_verification/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_partner_verification_documents', to=settings.AUTH_USER_MODEL)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.partnerverificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('case_worker', 'Case Worker'), ('viewer', 'Viewer')], default='viewer', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='partners.partnerorganisation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='unique_partner_member_per_organisation')],
            },
        ),
    ]
