# Generated by Django 6.1 on 2026-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerserviceconfiguration',
            name='rights_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partnerserviceconfiguration',
            name='support_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
