# Generated by Django 6.1 on 2026-08-26 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerserviceconfiguration_rights_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('referral_notifications', models.BooleanField(default=True)),
                ('verification_notifications', models.BooleanField(default=True)),
                ('product_updates', models.BooleanField(default=False)),
                ('show_public_phone', models.BooleanField(default=False)),
                ('show_public_email', models.BooleanField(default=False)),
                ('allow_remote_referrals', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='partners.partnerorganisation')),
            ],
        ),
    ]
