# Generated by Django 6.1 on 2026-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partnerpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganisation',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
