# Generated by Django 6.1 on 2026-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(blank=True, max_length=150)),
                ('coverage', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('review_required', 'Review Required'), ('expired', 'Expired'), ('archived', 'Archived')], default='review_required', max_length=30)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('next_verification_due', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
