# Generated by Django 6.1 on 2026-08-25 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportservice',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supportservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportservice',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supportservice',
            name='is_emergency_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportservice',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
