# Generated by Django 6.1 on 2026-08-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('review_required', 'Review Required'), ('expired', 'Expired'), ('archived', 'Archived')], default='review_required', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('standard', 'Standard'), ('sensitive', 'Sensitive'), ('high_risk', 'High Risk')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_safety_critical', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rights_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_steps', to='rights.rightstopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SituationRightsTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_links', to='rights.rightstopic')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights_links', to='rights.situation')),
            ],
            options={
                'unique_together': {('situation', 'rights_topic')},
            },
        ),
    ]
