# Generated by Django 6.1 on 2026-08-25 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0001_initial'),
        ('support', '0002_supportservice_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actionstep',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='situationrightstopic',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='actionstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionstep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rightstopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rightstopic',
            name='support_services',
            field=models.ManyToManyField(blank=True, related_name='rights_topics', to='support.supportservice'),
        ),
        migrations.AddField(
            model_name='rightstopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='situation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='situationrightstopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='situationrightstopic',
            constraint=models.UniqueConstraint(fields=('situation', 'rights_topic'), name='unique_situation_rights_topic'),
        ),
        migrations.AddField(
            model_name='safetyresponse',
            name='rights_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_responses', to='rights.rightstopic'),
        ),
        migrations.AddConstraint(
            model_name='safetyresponse',
            constraint=models.UniqueConstraint(fields=('rights_topic', 'trigger_key'), name='unique_rights_topic_safety_trigger'),
        ),
    ]
