# Generated by Django 6.1 on 2026-08-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_safetyresponse_alter_actionstep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightstopic',
            name='risk_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('sensitive', 'Sensitive'), ('high_risk', 'High Risk')], default='standard', max_length=20),
        ),
    ]
