# Generated by Django 6.1 on 2026-08-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_safetyresponse_alter_actionstep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.SlugField()),
                ('issue_slug', models.SlugField()),
                ('heading', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('evidence_items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rights_topics', models.ManyToManyField(blank=True, related_name='issue_outcomes', to='rights.rightstopic')),
                ('situation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_outcomes', to='rights.situation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category_slug', 'issue_slug'), name='unique_issue_outcome')],
            },
        ),
    ]
