# Generated by Django 6.1 on 2026-08-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_rightstopic_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalProvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('constitution', 'Constitution'), ('act', 'Act of Parliament'), ('regulation', 'Regulation'), ('statutory_instrument', 'Statutory Instrument'), ('case_law', 'Case Law'), ('international', 'International / Regional Instrument'), ('other', 'Other')], default='act', max_length=30)),
                ('law_title', models.CharField(max_length=255)),
                ('provision_reference', models.CharField(help_text="Specific legal reference, for example 'Article 21', 'Section 7(1)' or 'Regulation 4'.", max_length=150)),
                ('provision_heading', models.CharField(blank=True, max_length=255)),
                ('provision_text', models.TextField(blank=True, help_text='Reviewed extract or summary of the relevant legal provision. Do not store unverified AI-generated legal text here.')),
                ('plain_language_explanation', models.TextField(help_text='Citizen-facing explanation of the provision in clear, simple language.')),
                ('source_url', models.URLField(blank=True)),
                ('jurisdiction', models.CharField(default='Uganda', max_length=100)),
                ('reviewed_by', models.CharField(blank=True, max_length=255)),
                ('last_reviewed', models.DateField(blank=True, null=True)),
                ('next_review_due', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('review_required', 'Review Required'), ('expired', 'Expired'), ('archived', 'Archived')], default='review_required', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rights_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_provisions', to='rights.rightstopic')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('rights_topic', 'law_title', 'provision_reference'), name='unique_legal_provision_per_topic')],
            },
        ),
    ]
