# Generated by Django 6.1 on 2026-08-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0003_rightstopic_risk_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStepTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rights.actionstep')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action_step', 'language'), name='unique_action_step_translation')],
            },
        ),
        migrations.CreateModel(
            name='RightsTopicTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rights_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rights.rightstopic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rights_topic', 'language'), name='unique_rights_topic_translation')],
            },
        ),
        migrations.CreateModel(
            name='SafetyResponseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili'), ('nyn', 'Runyankole')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='rights.safetyresponse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('safety_response', 'language'), name='unique_safety_response_translation')],
            },
        ),
    ]
