# Generated by Django 6.1 on 2026-08-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0004_actionsteptranslation_rightstopictranslation_and_more'),
        ('rights', '0004_legalprovision'),
    ]

    operations = [
    ]
